name: Legg til begrep
description: Foresl책 et nytt begrep skal legges til
title: "[Nytt begrep 2]: "
labels: ["innhold", "nytt begrep"]
assignees:
  - panragon
body:
  - type: input
    id: summary
    attributes:
      label: Sammendrag
      description: Sammendrag av endringer du foresl책r
  - type: dropdown
    id: language
    attributes:
      label: Spr책kbasert referansesett
      options:
        - Norsk Bokm책l
        - Engelsk
        - Norsk Nynorsk
     validations:
      required: true
    - type: input
      id: FSN
      attributes:
        label: Nytt FSN (Fullstendig Spesifisert Navn)
      validations:
        required: true
    - type: input
      id: preferred-term
      attributes:
        label: Ny foretrukket term
      validations:
        required: true
    - type: input
      id: synonym
      attributes:
        label: Ny synonym
      validations:
        required: true
